#PYTHON STRING MANIPULATION
target = "Hello Meo"
tool = "Metasploit"
print("1.INDEXING - ACCESS CHARACTERS USING INDEXES.")
print(target[0])
print(target[1])
print(target[2])
print(target[0])
print("2. NEGATIVE INDEXING - ACCESSING CHARACTERS FROM END")
print(tool[-1])
print(tool[-2])
print(tool[-4])
print(tool[-10])
print("3. STING SLICING - EXTRACT PARTS FROM THE STRING")
print(target[0:2])
print(tool[::-1])
print("4.STING LENGTH - USED TO COUNT THE LENGTH OF THE STRING")
print(len(target))
print(len(tool))
print("5. LOWER - USED TO PRINT IN LOWERCASE")
print(target.lower())
print(tool.lower())
print("6. UPPER - USED TO PRINT IN UPPERCASE")
print(target.upper())
print(tool.upper())
print("7.STRIP - USED TO REMOVE SPACES FROM BEGINING - END")
text = "   hello   "
print(text.strip())
print("8. REPLACE - USED TO REPLACE TEXT")
print(target.replace("Metasploit", "Wireshark"))
print("9.SPLIT - USED TO BREAK STRING INTO PIECES")
text1 = "apple, banana, mango"
print(text1.split(","))
print("10. JOIN - JUST OPPOSITE TO SPLIT()")
text2 = ["i", "love", "cyber", "security"]
print("".join(text2))
print("11. FIND - USED TO SEARCH POSITION")
print(target.find("Meo"))
print("12.STARTSWITH() - USED TO SEARCH STARTS WITH PARTICULAR TEXT")
text3 = "https://hellohacker.com"
print(text3)
print(text3.startswith("https"))
print("13.ENDS WITH() - USED TO FIND LETTERS ENDS WITH PARTICULAR TEXT")
print(text3.endswith(".com"))
print("CONCATENATION - USED TO ADD TO STINGS")
print("target" + "found" + "tool_used" + "tool")
print("14.ESCAPE CHARACTERS")
print("lets\ndo\nit")
print("lets\tdoit")
print(target.isdigit())
print(tool.isalpha())

